MvcMovie/MvcMovie/Controllers/ReportController.cs
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Helpers;
using System.Web.Mvc;
using MvcMovie.Models;

namespace MvcMovie.Controllers
{
    public class ReportController : Controller
    {
        private MovieDBContext db = new MovieDBContext();

        public ActionResult Index()
        {
            return View();
        }

        private ActionResult GetChart(IEnumerable<string> xValues, IEnumerable<int> yValues)
        {
            var chart = new Chart(width: 300, height: 200)
                .AddSeries(
                    chartType: "bar",
                    xValue: xValues,
                    yValues: yValues)
                .GetBytes("png");

            return File(chart, "image/bytes");
        }

        public ActionResult ChartByGenre()
        {
            var query = from m in db.Movies
                group m by m.Genre
                into grp
                select new
                {
                    Genre = grp.Key,
                    Count = grp.Select(m => m.Title).Distinct().Count()
                };

            var genres = new List<string>();
            var counts = new List<int>();

            foreach (var row in query.OrderBy(m => m.Genre))
            {
                genres.Add(row.Genre);
                counts.Add(row.Count);
            }

            return GetChart(genres, counts);
        }

        public ActionResult ChartByRating()
        {
            var query = from m in db.Movies
                        group m by m.Rating
                            into grp
                            select new
                            {
                                Rating = grp.Key,
                                Count = grp.Select(m => m.Title).Distinct().Count()
                            };

            var ratings = new List<string>();
            var counts = new List<int>();

            foreach (var row in query.OrderBy(m => m.Rating))
            {
                ratings.Add(row.Rating);
                counts.Add(row.Count);
            }

            return GetChart(ratings, counts);
        }
    }
}

MvcMovie/MvcMovie/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Movie App</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Movies", "Index", "Movies", null, new { @class = "navbar-brand" })</li>
                    <li>@Html.ActionLink("Reports", "Index", "Report", null, new { @class = "navbar-brand" })</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>